### ISSUE TITLE
过早登录会掉线

### ISSUE THREAD

**Issue by sybb937** [PTYin/sdu-lib-seat#8]
大佬你好，非常感谢你的程序。我是编程小白，在使用过程中发现几个不明白的地方，大佬勿喷
1.  如过启动程序和进行预约的时间间隔比较长，它就难以选择设定好的座位号，即使设定的座位是空着，也无法成功约到；如果立即执行预约可以约到设定座位。
2.  还有一个就是，启动程序和进行预约的时间间隔比较长，会一直提示“由于长时间未操作，正在重新登录”，会花费很多时间。不清楚是不是我的cookie问题，我想它要是到点以后可以直接从头运行，或许也可以更流畅。

**Comment by sybb937** [comment]
> 大佬你好，非常感谢你的程序。 我是编程小白，在使用过程中发现几个不明白的地方，大佬勿喷
> 
> 1. 如过启动程序和进行预约的时间间隔比较长，它就难以选择设定好的座位号，即使设定的座位是空着，也无法成功约到； 如果立即执行预约可以约到设定座位。
> 2. 还有一个就是，启动程序和进行预约的时间间隔比较长，会一直提示“由于长时间未操作，正在重新登录”，会花费很多时间。 不清楚是不是我的cookie问题，我想它要是到点以后可以直接从头运行，或许也可以更流畅。

**Comment by ptyin** [comment]
哈喽，因为毕业好久没使用过这个脚本了。启动程序和进行预约的时间间隔不建议间隔太久，之前使用的时候5分钟左右是没太有问题的，可以通过linux自带的crontab定时启动的方式定时启动脚本。

**Comment by sybb937** [comment]
哈哈哈，好的，谢谢你，我懂了大佬



在 2022-06-21 10:16:29，"Xiangkun Yin" ***@***.***> 写道：

哈喽，因为毕业好久没使用过这个脚本了。启动程序和进行预约的时间间隔不建议间隔太久，之前使用的时候5分钟左右是没太有问题的，可以通过linux自带的crontab定时启动的方式定时启动脚本。
